### ISSUE TITLE
[Investigate] Pre/Post Support

### ISSUE THREAD

**Issue by ncalteen** [github/local-action#183]
Currently `pre` and `post` steps are ignored by `@github/local-action`. It would be useful to implement these. Initially, they would only support running other JavaScript action code.

```yaml
runs:
  using: node20
  main: main.js
  post: cleanup.js
```

It is important to note that information can be passed between `pre`, `post`, and "main" using `GITHUB_STATE`/`getState`/`saveState` ([ref](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#sending-values-to-the-pre-and-post-actions)).
